### ISSUE TITLE
Contributing - no longer up to date?

### ISSUE THREAD

**Issue by n9** [basarat/typescript-services#1]
After building the compiler (according to the instructions), there is no `typescriptServices.d.ts` in `build/local`. How to get it?

(I would like to update the compiler, since the current version of services seems to put whole content of a file into the `SourceUnit.fileName()` instead of the name of file.)

**Comment by basarat** [comment]
@n9 sorry for the late reply. Updated : https://github.com/basarat/typescript-services/blob/master/README.md#getting-the-language-service
